apiVersion: connection.dfcloud.m.funnelflux.pro/v1alpha1
kind: Connection
metadata:
  name: example-connection
spec:
  forProvider:
    name: example-connection
    networkIdRef:
      name: example-network
    peer:
      accountId: 'example-project'
      vpcId: 'example-vpc'
  providerConfigRef:
    kind: ProviderConfig
    name: default
