// SPDX-FileCopyrightText: 2024 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ClusterInitParameters struct {

	// The cluster shard memory in bytes. For example, `6250000000` represents 6.25 GB. If not set, the shard memory is managed automatically.
	//
	// Permitted values: `6250000000` (6.25 GB), `12500000000` (12.5 GB), `25000000000` (25 GB), `50000000000` (50 GB), `100000000000` (100 GB).
	ShardMemory *float64 `json:"shardMemory,omitempty" tf:"shard_memory,omitempty"`
}

type ClusterObservation struct {

	// The cluster shard memory in bytes. For example, `6250000000` represents 6.25 GB. If not set, the shard memory is managed automatically.
	//
	// Permitted values: `6250000000` (6.25 GB), `12500000000` (12.5 GB), `25000000000` (25 GB), `50000000000` (50 GB), `100000000000` (100 GB).
	ShardMemory *float64 `json:"shardMemory,omitempty" tf:"shard_memory,omitempty"`
}

type ClusterParameters struct {

	// The cluster shard memory in bytes. For example, `6250000000` represents 6.25 GB. If not set, the shard memory is managed automatically.
	//
	// Permitted values: `6250000000` (6.25 GB), `12500000000` (12.5 GB), `25000000000` (25 GB), `50000000000` (50 GB), `100000000000` (100 GB).
	// +kubebuilder:validation:Optional
	ShardMemory *float64 `json:"shardMemory,omitempty" tf:"shard_memory,omitempty"`
}

type DatastoreInitParameters struct {
	Cluster *ClusterInitParameters `json:"cluster,omitempty" tf:"cluster,omitempty"`

	// Disable the passkey for the datastore.
	DisablePassKey *bool `json:"disablePassKey,omitempty" tf:"disable_pass_key,omitempty"`

	Dragonfly *DragonflyInitParameters `json:"dragonfly,omitempty" tf:"dragonfly,omitempty"`

	Location *LocationInitParameters `json:"location,omitempty" tf:"location,omitempty"`

	MaintenanceWindow *MaintenanceWindowInitParameters `json:"maintenanceWindow,omitempty" tf:"maintenance_window,omitempty"`

	// The name of the datastore.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the network the datastore should be placed into.
	// +crossplane:generate:reference:type=github.com/funnelflux/provider-dfcloud/apis/namespaced/network/v1alpha1.Network
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Network in network to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v1.NamespacedReference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Network in network to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v1.NamespacedSelector `json:"networkIdSelector,omitempty" tf:"-"`

	Tier *TierInitParameters `json:"tier,omitempty" tf:"tier,omitempty"`
}

type DatastoreObservation struct {

	// The address of the datastore.
	Addr *string `json:"addr,omitempty" tf:"addr,omitempty"`

	Cluster *ClusterObservation `json:"cluster,omitempty" tf:"cluster,omitempty"`

	// The timestamp when the datastore was created.
	CreatedAt *float64 `json:"createdAt,omitempty" tf:"created_at,omitempty"`

	// Disable the passkey for the datastore.
	DisablePassKey *bool `json:"disablePassKey,omitempty" tf:"disable_pass_key,omitempty"`

	Dragonfly *DragonflyObservation `json:"dragonfly,omitempty" tf:"dragonfly,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	Location *LocationObservation `json:"location,omitempty" tf:"location,omitempty"`

	MaintenanceWindow *MaintenanceWindowObservation `json:"maintenanceWindow,omitempty" tf:"maintenance_window,omitempty"`

	// The name of the datastore.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the network the datastore should be placed into.
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	Tier *TierObservation `json:"tier,omitempty" tf:"tier,omitempty"`
}

type DatastoreParameters struct {

	// +kubebuilder:validation:Optional
	Cluster *ClusterParameters `json:"cluster,omitempty" tf:"cluster,omitempty"`

	// Disable the passkey for the datastore.
	// +kubebuilder:validation:Optional
	DisablePassKey *bool `json:"disablePassKey,omitempty" tf:"disable_pass_key,omitempty"`

	// +kubebuilder:validation:Optional
	Dragonfly *DragonflyParameters `json:"dragonfly,omitempty" tf:"dragonfly,omitempty"`

	// +kubebuilder:validation:Optional
	Location *LocationParameters `json:"location,omitempty" tf:"location,omitempty"`

	// +kubebuilder:validation:Optional
	MaintenanceWindow *MaintenanceWindowParameters `json:"maintenanceWindow,omitempty" tf:"maintenance_window,omitempty"`

	// The name of the datastore.
	// +kubebuilder:validation:Optional
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The ID of the network the datastore should be placed into.
	// +crossplane:generate:reference:type=github.com/funnelflux/provider-dfcloud/apis/namespaced/network/v1alpha1.Network
	// +kubebuilder:validation:Optional
	NetworkID *string `json:"networkId,omitempty" tf:"network_id,omitempty"`

	// Reference to a Network in network to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDRef *v1.NamespacedReference `json:"networkIdRef,omitempty" tf:"-"`

	// Selector for a Network in network to populate networkId.
	// +kubebuilder:validation:Optional
	NetworkIDSelector *v1.NamespacedSelector `json:"networkIdSelector,omitempty" tf:"-"`

	// +kubebuilder:validation:Optional
	Tier *TierParameters `json:"tier,omitempty" tf:"tier,omitempty"`
}

type DragonflyInitParameters struct {
	ACLRules []*string `json:"aclRulesSecretRef,omitempty" tf:"-"`

	// Enable BullMQ compatibility.
	Bullmq *bool `json:"bullmq,omitempty" tf:"bullmq,omitempty"`

	// Enable cache mode for memory management.
	CacheMode *bool `json:"cacheMode,omitempty" tf:"cache_mode,omitempty"`

	// Enable Memcached protocol.
	Memcached *bool `json:"memcached,omitempty" tf:"memcached,omitempty"`

	// Enable Sidekiq compatibility.
	Sidekiq *bool `json:"sidekiq,omitempty" tf:"sidekiq,omitempty"`

	// Enable TLS.
	TLS *bool `json:"tls,omitempty" tf:"tls,omitempty"`
}

type DragonflyObservation struct {

	// Enable BullMQ compatibility.
	Bullmq *bool `json:"bullmq,omitempty" tf:"bullmq,omitempty"`

	// Enable cache mode for memory management.
	CacheMode *bool `json:"cacheMode,omitempty" tf:"cache_mode,omitempty"`

	// Enable Memcached protocol.
	Memcached *bool `json:"memcached,omitempty" tf:"memcached,omitempty"`

	// Enable Sidekiq compatibility.
	Sidekiq *bool `json:"sidekiq,omitempty" tf:"sidekiq,omitempty"`

	// Enable TLS.
	TLS *bool `json:"tls,omitempty" tf:"tls,omitempty"`
}

type DragonflyParameters struct {

	// List of ACL rules.
	// +kubebuilder:validation:Optional
	ACLRulesSecretRef *[]v1.LocalSecretKeySelector `json:"aclRulesSecretRef,omitempty" tf:"-"`

	// Enable BullMQ compatibility.
	// +kubebuilder:validation:Optional
	Bullmq *bool `json:"bullmq,omitempty" tf:"bullmq,omitempty"`

	// Enable cache mode for memory management.
	// +kubebuilder:validation:Optional
	CacheMode *bool `json:"cacheMode,omitempty" tf:"cache_mode,omitempty"`

	// Enable Memcached protocol.
	// +kubebuilder:validation:Optional
	Memcached *bool `json:"memcached,omitempty" tf:"memcached,omitempty"`

	// Enable Sidekiq compatibility.
	// +kubebuilder:validation:Optional
	Sidekiq *bool `json:"sidekiq,omitempty" tf:"sidekiq,omitempty"`

	// Enable TLS.
	// +kubebuilder:validation:Optional
	TLS *bool `json:"tls,omitempty" tf:"tls,omitempty"`
}

type LocationInitParameters struct {

	// The availability zones for the datastore location.
	AvailabilityZones []*string `json:"availabilityZones,omitempty" tf:"availability_zones,omitempty"`

	// The provider for the datastore location.
	Provider *string `json:"provider,omitempty" tf:"provider,omitempty"`

	// The region for the datastore location.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type LocationObservation struct {

	// The availability zones for the datastore location.
	AvailabilityZones []*string `json:"availabilityZones,omitempty" tf:"availability_zones,omitempty"`

	// The provider for the datastore location.
	Provider *string `json:"provider,omitempty" tf:"provider,omitempty"`

	// The region for the datastore location.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`
}

type LocationParameters struct {

	// The availability zones for the datastore location.
	// +kubebuilder:validation:Optional
	AvailabilityZones []*string `json:"availabilityZones,omitempty" tf:"availability_zones,omitempty"`

	// The provider for the datastore location.
	// +kubebuilder:validation:Optional
	Provider *string `json:"provider" tf:"provider,omitempty"`

	// The region for the datastore location.
	// +kubebuilder:validation:Optional
	Region *string `json:"region" tf:"region,omitempty"`
}

type MaintenanceWindowInitParameters struct {

	// DurationHours is the duration of the maintenance window in hours. 0 means maintenance is always allowed.
	DurationHours *float64 `json:"durationHours,omitempty" tf:"duration_hours,omitempty"`

	// The hour of the day to start the maintenance window. 0-23.
	Hour *float64 `json:"hour,omitempty" tf:"hour,omitempty"`

	// The day of the week to start the maintenance window. 0-6, 0 is Sunday.
	Weekday *float64 `json:"weekday,omitempty" tf:"weekday,omitempty"`
}

type MaintenanceWindowObservation struct {

	// DurationHours is the duration of the maintenance window in hours. 0 means maintenance is always allowed.
	DurationHours *float64 `json:"durationHours,omitempty" tf:"duration_hours,omitempty"`

	// The hour of the day to start the maintenance window. 0-23.
	Hour *float64 `json:"hour,omitempty" tf:"hour,omitempty"`

	// The day of the week to start the maintenance window. 0-6, 0 is Sunday.
	Weekday *float64 `json:"weekday,omitempty" tf:"weekday,omitempty"`
}

type MaintenanceWindowParameters struct {

	// DurationHours is the duration of the maintenance window in hours. 0 means maintenance is always allowed.
	// +kubebuilder:validation:Optional
	DurationHours *float64 `json:"durationHours,omitempty" tf:"duration_hours,omitempty"`

	// The hour of the day to start the maintenance window. 0-23.
	// +kubebuilder:validation:Optional
	Hour *float64 `json:"hour,omitempty" tf:"hour,omitempty"`

	// The day of the week to start the maintenance window. 0-6, 0 is Sunday.
	// +kubebuilder:validation:Optional
	Weekday *float64 `json:"weekday,omitempty" tf:"weekday,omitempty"`
}

type TierInitParameters struct {

	// The maximum memory (in bytes) for the datastore. For example, `12500000000` represents 12.5 GB.
	//
	// The permitted values listed below apply to non-swarm datastores. For swarm datastores, the value must be a multiple of `shard_memory` (e.g. `shard_memory` × number of shards).
	//
	// Permitted values by cloud provider and performance tier (non-swarm):
	//
	// | Provider | Tier     | Permitted values (bytes)                                                                                       |
	// |----------|----------|----------------------------------------------------------------------------------------------------------------|
	// | AWS      | dev      | `3e9`                                                                                                          |
	// | AWS      | byoc     | `6.25e9`, `12.5e9`, `25e9`, `50e9`, `100e9`, `200e9`, `400e9`                                                 |
	// | AWS      | standard | `12.5e9`, `25e9`, `50e9`, `100e9`, `200e9`, `400e9`                                                           |
	// | AWS      | enhanced | `6.25e9`, `12.5e9`, `25e9`, `50e9`, `100e9`, `200e9`, `300e9`, `400e9`                                        |
	// | AWS      | extreme  | `6.25e9`, `12.5e9`, `25e9`, `50e9`, `100e9`, `200e9`                                                          |
	// | GCP      | dev      | `3e9`                                                                                                          |
	// | GCP      | byoc     | `6.25e9`, `12.5e9`, `25e9`, `50e9`, `100e9`, `200e9`, `300e9`, `400e9`                                        |
	// | GCP      | standard | `12.5e9`, `25e9`, `50e9`, `100e9`, `200e9`, `300e9`, `400e9`                                                  |
	// | GCP      | enhanced | `6.25e9`, `12.5e9`, `25e9`, `50e9`, `100e9`, `150e9`, `200e9`, `250e9`, `300e9`, `400e9`                      |
	// | GCP      | extreme  | `6.25e9`, `12.5e9`, `25e9`, `50e9`, `100e9`, `150e9`, `200e9`                                                 |
	// | Azure    | dev      | `3e9`                                                                                                          |
	// | Azure    | standard | `12.5e9`, `25e9`, `50e9`, `100e9`, `200e9`, `300e9`, `400e9`                                                  |
	// | Azure    | enhanced | `6.5e9`, `12.5e9`, `25e9`, `50e9`, `100e9`, `150e9`, `200e9`, `300e9`                                         |
	// | Azure    | extreme  | `6.5e9`, `12.5e9`, `25e9`, `50e9`, `100e9`                                                                    |
	MaxMemoryBytes *float64 `json:"maxMemoryBytes,omitempty" tf:"max_memory_bytes,omitempty"`

	// The performance tier for the datastore.
	PerformanceTier *string `json:"performanceTier,omitempty" tf:"performance_tier,omitempty"`

	// The number of replicas for the datastore. Default is 0.
	Replicas *float64 `json:"replicas,omitempty" tf:"replicas,omitempty"`
}

type TierObservation struct {

	// The maximum memory (in bytes) for the datastore. For example, `12500000000` represents 12.5 GB.
	//
	// The permitted values listed below apply to non-swarm datastores. For swarm datastores, the value must be a multiple of `shard_memory` (e.g. `shard_memory` × number of shards).
	//
	// Permitted values by cloud provider and performance tier (non-swarm):
	//
	// | Provider | Tier     | Permitted values (bytes)                                                                                       |
	// |----------|----------|----------------------------------------------------------------------------------------------------------------|
	// | AWS      | dev      | `3e9`                                                                                                          |
	// | AWS      | byoc     | `6.25e9`, `12.5e9`, `25e9`, `50e9`, `100e9`, `200e9`, `400e9`                                                 |
	// | AWS      | standard | `12.5e9`, `25e9`, `50e9`, `100e9`, `200e9`, `400e9`                                                           |
	// | AWS      | enhanced | `6.25e9`, `12.5e9`, `25e9`, `50e9`, `100e9`, `200e9`, `300e9`, `400e9`                                        |
	// | AWS      | extreme  | `6.25e9`, `12.5e9`, `25e9`, `50e9`, `100e9`, `200e9`                                                          |
	// | GCP      | dev      | `3e9`                                                                                                          |
	// | GCP      | byoc     | `6.25e9`, `12.5e9`, `25e9`, `50e9`, `100e9`, `200e9`, `300e9`, `400e9`                                        |
	// | GCP      | standard | `12.5e9`, `25e9`, `50e9`, `100e9`, `200e9`, `300e9`, `400e9`                                                  |
	// | GCP      | enhanced | `6.25e9`, `12.5e9`, `25e9`, `50e9`, `100e9`, `150e9`, `200e9`, `250e9`, `300e9`, `400e9`                      |
	// | GCP      | extreme  | `6.25e9`, `12.5e9`, `25e9`, `50e9`, `100e9`, `150e9`, `200e9`                                                 |
	// | Azure    | dev      | `3e9`                                                                                                          |
	// | Azure    | standard | `12.5e9`, `25e9`, `50e9`, `100e9`, `200e9`, `300e9`, `400e9`                                                  |
	// | Azure    | enhanced | `6.5e9`, `12.5e9`, `25e9`, `50e9`, `100e9`, `150e9`, `200e9`, `300e9`                                         |
	// | Azure    | extreme  | `6.5e9`, `12.5e9`, `25e9`, `50e9`, `100e9`                                                                    |
	MaxMemoryBytes *float64 `json:"maxMemoryBytes,omitempty" tf:"max_memory_bytes,omitempty"`

	// The performance tier for the datastore.
	PerformanceTier *string `json:"performanceTier,omitempty" tf:"performance_tier,omitempty"`

	// The number of replicas for the datastore. Default is 0.
	Replicas *float64 `json:"replicas,omitempty" tf:"replicas,omitempty"`
}

type TierParameters struct {

	// The maximum memory (in bytes) for the datastore. For example, `12500000000` represents 12.5 GB.
	//
	// The permitted values listed below apply to non-swarm datastores. For swarm datastores, the value must be a multiple of `shard_memory` (e.g. `shard_memory` × number of shards).
	//
	// Permitted values by cloud provider and performance tier (non-swarm):
	//
	// | Provider | Tier     | Permitted values (bytes)                                                                                       |
	// |----------|----------|----------------------------------------------------------------------------------------------------------------|
	// | AWS      | dev      | `3e9`                                                                                                          |
	// | AWS      | byoc     | `6.25e9`, `12.5e9`, `25e9`, `50e9`, `100e9`, `200e9`, `400e9`                                                 |
	// | AWS      | standard | `12.5e9`, `25e9`, `50e9`, `100e9`, `200e9`, `400e9`                                                           |
	// | AWS      | enhanced | `6.25e9`, `12.5e9`, `25e9`, `50e9`, `100e9`, `200e9`, `300e9`, `400e9`                                        |
	// | AWS      | extreme  | `6.25e9`, `12.5e9`, `25e9`, `50e9`, `100e9`, `200e9`                                                          |
	// | GCP      | dev      | `3e9`                                                                                                          |
	// | GCP      | byoc     | `6.25e9`, `12.5e9`, `25e9`, `50e9`, `100e9`, `200e9`, `300e9`, `400e9`                                        |
	// | GCP      | standard | `12.5e9`, `25e9`, `50e9`, `100e9`, `200e9`, `300e9`, `400e9`                                                  |
	// | GCP      | enhanced | `6.25e9`, `12.5e9`, `25e9`, `50e9`, `100e9`, `150e9`, `200e9`, `250e9`, `300e9`, `400e9`                      |
	// | GCP      | extreme  | `6.25e9`, `12.5e9`, `25e9`, `50e9`, `100e9`, `150e9`, `200e9`                                                 |
	// | Azure    | dev      | `3e9`                                                                                                          |
	// | Azure    | standard | `12.5e9`, `25e9`, `50e9`, `100e9`, `200e9`, `300e9`, `400e9`                                                  |
	// | Azure    | enhanced | `6.5e9`, `12.5e9`, `25e9`, `50e9`, `100e9`, `150e9`, `200e9`, `300e9`                                         |
	// | Azure    | extreme  | `6.5e9`, `12.5e9`, `25e9`, `50e9`, `100e9`                                                                    |
	// +kubebuilder:validation:Optional
	MaxMemoryBytes *float64 `json:"maxMemoryBytes" tf:"max_memory_bytes,omitempty"`

	// The performance tier for the datastore.
	// +kubebuilder:validation:Optional
	PerformanceTier *string `json:"performanceTier" tf:"performance_tier,omitempty"`

	// The number of replicas for the datastore. Default is 0.
	// +kubebuilder:validation:Optional
	Replicas *float64 `json:"replicas,omitempty" tf:"replicas,omitempty"`
}

// DatastoreSpec defines the desired state of Datastore
type DatastoreSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            DatastoreParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider DatastoreInitParameters `json:"initProvider,omitempty"`
}

// DatastoreStatus defines the observed state of Datastore.
type DatastoreStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        DatastoreObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// Datastore is the Schema for the Datastores API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,dfcloud}
type Datastore struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.location) || (has(self.initProvider) && has(self.initProvider.location))",message="spec.forProvider.location is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.name) || (has(self.initProvider) && has(self.initProvider.name))",message="spec.forProvider.name is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.tier) || (has(self.initProvider) && has(self.initProvider.tier))",message="spec.forProvider.tier is a required parameter"
	Spec   DatastoreSpec   `json:"spec"`
	Status DatastoreStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// DatastoreList contains a list of Datastores
type DatastoreList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []Datastore `json:"items"`
}

// Repository type metadata.
var (
	Datastore_Kind             = "Datastore"
	Datastore_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: Datastore_Kind}.String()
	Datastore_KindAPIVersion   = Datastore_Kind + "." + CRDGroupVersion.String()
	Datastore_GroupVersionKind = CRDGroupVersion.WithKind(Datastore_Kind)
)

func init() {
	SchemeBuilder.Register(&Datastore{}, &DatastoreList{})
}
